name: wpsite

recipe: wordpress

config:
  webroot: .
  php: '7.4'
  via: nginx
  database: mariadb
  xdebug: true
  ssl: true
  config:
    php: .config/php.ini

services:
  database:
    portforward: true
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database

proxy:
  mailhog:
    - mailhog.wpsite.lndo.site
  pma:
    - db.wpsite.lndo.site
