name: mysite
recipe: wordpress
config:
  webroot: .
  php: '7.4'
  via: nginx
  database: mariadb
  xdebug: true
  config:
    php: .config/php.ini
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
proxy:
  mailhog:
    - mail.mysite.lndo.site
  pma:
    - db.mysite.lndo.site
